[2023-08-28T21:56:44.101+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-28T21:56:41.870078+00:00 [queued]>
[2023-08-28T21:56:44.111+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-28T21:56:41.870078+00:00 [queued]>
[2023-08-28T21:56:44.112+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-28T21:56:44.128+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_crypto_data_task> on 2023-08-28 21:56:41.870078+00:00
[2023-08-28T21:56:44.135+0000] {standard_task_runner.py:57} INFO - Started process 3094 to run task
[2023-08-28T21:56:44.140+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'download_crypto_data_task', 'manual__2023-08-28T21:56:41.870078+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmptyvn0qaw']
[2023-08-28T21:56:44.145+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask download_crypto_data_task
[2023-08-28T21:56:44.203+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-28T21:56:41.870078+00:00 [running]> on host e5729120e4b7
[2023-08-28T21:56:44.295+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='download_crypto_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T21:56:41.870078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-28T21:56:41.870078+00:00'
[2023-08-28T21:56:44.445+0000] {logging_mixin.py:151} INFO - https://api.coingecko.com/api/v3/coins/bitcoin/history?date=01-08-2023
[2023-08-28T21:56:44.446+0000] {logging_mixin.py:151} INFO - Data for 01-08-2023 downloaded and saved to crypto_data_01-08-2023.json!
[2023-08-28T21:56:44.447+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 50, in download_crypto_data_for_range
    download_crypto_data_for_date(current_date.strftime('%d-%m-%Y'))
  File "/opt/airflow/dags/coin_data_dag.py", line 43, in download_crypto_data_for_date
    pg_hook = PostgresHook(postgres_conn_id='postgres_localhost')
NameError: name 'PostgresHook' is not defined
[2023-08-28T21:56:44.458+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=download_crypto_data_task, execution_date=20230828T215641, start_date=20230828T215644, end_date=20230828T215644
[2023-08-28T21:56:44.472+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task download_crypto_data_task (name 'PostgresHook' is not defined; 3094)
[2023-08-28T21:56:44.514+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-28T21:56:44.536+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
