[2023-08-29T00:49:58.034+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.create_table_task manual__2023-08-29T00:49:55.877507+00:00 [queued]>
[2023-08-29T00:49:58.043+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.create_table_task manual__2023-08-29T00:49:55.877507+00:00 [queued]>
[2023-08-29T00:49:58.044+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T00:49:58.059+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): create_table_task> on 2023-08-29 00:49:55.877507+00:00
[2023-08-29T00:49:58.065+0000] {standard_task_runner.py:57} INFO - Started process 622 to run task
[2023-08-29T00:49:58.070+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'create_table_task', 'manual__2023-08-29T00:49:55.877507+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmp6fc4sqbj']
[2023-08-29T00:49:58.075+0000] {standard_task_runner.py:85} INFO - Job 119: Subtask create_table_task
[2023-08-29T00:49:58.132+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.create_table_task manual__2023-08-29T00:49:55.877507+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T00:49:58.225+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NicoB' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:49:55.877507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T00:49:55.877507+00:00'
[2023-08-29T00:49:58.237+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-08-29T00:49:58.242+0000] {sql.py:418} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS coin_data (
        coin_id VARCHAR NOT NULL, 
        date DATE NOT NULL, 
        price FLOAT, 
        json JSON, 
        PRIMARY KEY (coin, date)
    );
    , parameters: None
[2023-08-29T00:49:58.244+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 30, in create_coin_data_table_if_not_exists
    pg_hook.run(create_table_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "coin" named in key does not exist
LINE 7:         PRIMARY KEY (coin, date)
                ^

[2023-08-29T00:49:58.256+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=create_table_task, execution_date=20230829T004955, start_date=20230829T004958, end_date=20230829T004958
[2023-08-29T00:49:58.270+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 119 for task create_table_task (column "coin" named in key does not exist
LINE 7:         PRIMARY KEY (coin, date)
                ^
; 622)
[2023-08-29T00:49:58.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T00:49:58.315+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
