[2023-08-28T22:18:54.254+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-28T22:18:52.664921+00:00 [queued]>
[2023-08-28T22:18:54.263+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-28T22:18:52.664921+00:00 [queued]>
[2023-08-28T22:18:54.263+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-28T22:18:54.277+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_crypto_data_task> on 2023-08-28 22:18:52.664921+00:00
[2023-08-28T22:18:54.283+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2023-08-28T22:18:54.292+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'download_crypto_data_task', 'manual__2023-08-28T22:18:52.664921+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmprqky_nyx']
[2023-08-28T22:18:54.297+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask download_crypto_data_task
[2023-08-28T22:18:54.363+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-28T22:18:52.664921+00:00 [running]> on host 8236b6ef9166
[2023-08-28T22:18:54.471+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='download_crypto_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T22:18:52.664921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-28T22:18:52.664921+00:00'
[2023-08-28T22:18:54.589+0000] {logging_mixin.py:151} INFO - https://api.coingecko.com/api/v3/coins/bitcoin/history?date=01-08-2023
[2023-08-28T22:18:54.591+0000] {logging_mixin.py:151} INFO - Data for 01-08-2023 downloaded and saved to crypto_data_01-08-2023.json!
[2023-08-28T22:18:54.603+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-08-28T22:18:54.605+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 50, in download_crypto_data_for_range
    download_crypto_data_for_date(current_date.strftime('%d-%m-%Y'))
  File "/opt/airflow/dags/coin_data_dag.py", line 44, in download_crypto_data_for_date
    pg_hook.run(insert_query, parameters=(coin_id, price_usd, date, json.dumps(data)))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5423 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5423 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-08-28T22:18:54.618+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=download_crypto_data_task, execution_date=20230828T221852, start_date=20230828T221854, end_date=20230828T221854
[2023-08-28T22:18:54.634+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 71 for task download_crypto_data_task (connection to server at "localhost" (127.0.0.1), port 5423 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5423 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 87)
[2023-08-28T22:18:54.667+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-28T22:18:54.690+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
