[2023-08-29T01:34:28.840+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:29:23.515696+00:00 [queued]>
[2023-08-29T01:34:28.852+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:29:23.515696+00:00 [queued]>
[2023-08-29T01:34:28.853+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-29T01:34:28.871+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_store_task> on 2023-08-29 01:29:23.515696+00:00
[2023-08-29T01:34:28.878+0000] {standard_task_runner.py:57} INFO - Started process 1358 to run task
[2023-08-29T01:34:28.883+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'fetch_and_store_task', 'manual__2023-08-29T01:29:23.515696+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmpmj8ofm_2']
[2023-08-29T01:34:28.888+0000] {standard_task_runner.py:85} INFO - Job 141: Subtask fetch_and_store_task
[2023-08-29T01:34:28.954+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:29:23.515696+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T01:34:29.061+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NicoB' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='fetch_and_store_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T01:29:23.515696+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T01:29:23.515696+00:00'
[2023-08-29T01:34:29.205+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 57, in fetch_and_store_crypto_data_for_range
    fetch_and_store_crypto_data_for_date(current_date.strftime('%d-%m-%Y'))
  File "/opt/airflow/dags/coin_data_dag.py", line 42, in fetch_and_store_crypto_data_for_date
    date = date.strftime('%Y-%m-%d')
AttributeError: 'str' object has no attribute 'strftime'
[2023-08-29T01:34:29.216+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crypto_data_download, task_id=fetch_and_store_task, execution_date=20230829T012923, start_date=20230829T013428, end_date=20230829T013429
[2023-08-29T01:34:29.232+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 141 for task fetch_and_store_task ('str' object has no attribute 'strftime'; 1358)
[2023-08-29T01:34:29.257+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T01:34:29.304+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
