[2023-08-29T01:43:33.686+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:43:29.800583+00:00 [queued]>
[2023-08-29T01:43:33.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:43:29.800583+00:00 [queued]>
[2023-08-29T01:43:33.697+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T01:43:33.712+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_store_task> on 2023-08-29 01:43:29.800583+00:00
[2023-08-29T01:43:33.718+0000] {standard_task_runner.py:57} INFO - Started process 1513 to run task
[2023-08-29T01:43:33.723+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'fetch_and_store_task', 'manual__2023-08-29T01:43:29.800583+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmp8jp0j9b9']
[2023-08-29T01:43:33.729+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask fetch_and_store_task
[2023-08-29T01:43:33.790+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:43:29.800583+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T01:43:33.887+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NicoB' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='fetch_and_store_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T01:43:29.800583+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T01:43:29.800583+00:00'
[2023-08-29T01:43:33.889+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 47, in fetch_and_store_crypto_data_for_range
    fetch_and_store_crypto_data_for_date(current_date.strftime('%d-%m-%Y'))
AttributeError: 'str' object has no attribute 'strftime'
[2023-08-29T01:43:33.901+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=fetch_and_store_task, execution_date=20230829T014329, start_date=20230829T014333, end_date=20230829T014333
[2023-08-29T01:43:33.914+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task fetch_and_store_task ('str' object has no attribute 'strftime'; 1513)
[2023-08-29T01:43:33.936+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T01:43:33.956+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
