[2023-08-29T00:36:32.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-29T00:36:28.416259+00:00 [queued]>
[2023-08-29T00:36:32.523+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-29T00:36:28.416259+00:00 [queued]>
[2023-08-29T00:36:32.523+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T00:36:32.545+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): download_crypto_data_task> on 2023-08-29 00:36:28.416259+00:00
[2023-08-29T00:36:32.551+0000] {standard_task_runner.py:57} INFO - Started process 382 to run task
[2023-08-29T00:36:32.558+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'download_crypto_data_task', 'manual__2023-08-29T00:36:28.416259+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmpqtnnyle7']
[2023-08-29T00:36:32.563+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask download_crypto_data_task
[2023-08-29T00:36:32.624+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.download_crypto_data_task manual__2023-08-29T00:36:28.416259+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T00:36:32.746+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NicoB' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='download_crypto_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:36:28.416259+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T00:36:28.416259+00:00'
[2023-08-29T00:36:32.864+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 61, in download_crypto_data_for_range
    download_crypto_data_for_date(current_date.strftime('%d-%m-%Y'))
  File "/opt/airflow/dags/coin_data_dag.py", line 56, in download_crypto_data_for_date
    insert_task.execute()
TypeError: execute() missing 1 required positional argument: 'context'
[2023-08-29T00:36:32.875+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=download_crypto_data_task, execution_date=20230829T003628, start_date=20230829T003632, end_date=20230829T003632
[2023-08-29T00:36:32.889+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 106 for task download_crypto_data_task (execute() missing 1 required positional argument: 'context'; 382)
[2023-08-29T00:36:32.933+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T00:36:32.952+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
