[2023-08-29T00:43:46.982+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T00:43:42.973454+00:00 [queued]>
[2023-08-29T00:43:46.993+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T00:43:42.973454+00:00 [queued]>
[2023-08-29T00:43:46.994+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T00:43:47.010+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_store_task> on 2023-08-29 00:43:42.973454+00:00
[2023-08-29T00:43:47.017+0000] {standard_task_runner.py:57} INFO - Started process 510 to run task
[2023-08-29T00:43:47.022+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'fetch_and_store_task', 'manual__2023-08-29T00:43:42.973454+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmplxmuye5j']
[2023-08-29T00:43:47.026+0000] {standard_task_runner.py:85} INFO - Job 114: Subtask fetch_and_store_task
[2023-08-29T00:43:47.089+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T00:43:42.973454+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T00:43:47.184+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NicoB' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='fetch_and_store_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:43:42.973454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T00:43:42.973454+00:00'
[2023-08-29T00:43:47.187+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: fetch_and_store_crypto_data_for_range() missing 2 required positional arguments: 'start_date' and 'end_date'
[2023-08-29T00:43:47.197+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=fetch_and_store_task, execution_date=20230829T004342, start_date=20230829T004346, end_date=20230829T004347
[2023-08-29T00:43:47.209+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 114 for task fetch_and_store_task (fetch_and_store_crypto_data_for_range() missing 2 required positional arguments: 'start_date' and 'end_date'; 510)
[2023-08-29T00:43:47.235+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T00:43:47.256+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
