[2023-08-29T01:34:03.308+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:33:59.547732+00:00 [queued]>
[2023-08-29T01:34:03.321+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:33:59.547732+00:00 [queued]>
[2023-08-29T01:34:03.322+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T01:34:03.348+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_store_task> on 2023-08-29 01:33:59.547732+00:00
[2023-08-29T01:34:03.371+0000] {standard_task_runner.py:57} INFO - Started process 1355 to run task
[2023-08-29T01:34:03.377+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'fetch_and_store_task', 'manual__2023-08-29T01:33:59.547732+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmpoovo7z38']
[2023-08-29T01:34:03.381+0000] {standard_task_runner.py:85} INFO - Job 140: Subtask fetch_and_store_task
[2023-08-29T01:34:03.454+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.fetch_and_store_task manual__2023-08-29T01:33:59.547732+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T01:34:03.565+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NicoB' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='fetch_and_store_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T01:33:59.547732+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T01:33:59.547732+00:00'
[2023-08-29T01:34:03.697+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coin_data_dag.py", line 57, in fetch_and_store_crypto_data_for_range
    fetch_and_store_crypto_data_for_date(current_date.strftime('%d-%m-%Y'))
  File "/opt/airflow/dags/coin_data_dag.py", line 42, in fetch_and_store_crypto_data_for_date
    date = date.strftime('%Y-%m-%d')
AttributeError: 'str' object has no attribute 'strftime'
[2023-08-29T01:34:03.709+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=fetch_and_store_task, execution_date=20230829T013359, start_date=20230829T013403, end_date=20230829T013403
[2023-08-29T01:34:03.725+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 140 for task fetch_and_store_task ('str' object has no attribute 'strftime'; 1355)
[2023-08-29T01:34:03.755+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T01:34:03.783+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
