[2023-08-29T00:22:21.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_data_download.create_books_table manual__2023-08-29T00:22:19.916454+00:00 [queued]>
[2023-08-29T00:22:21.647+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_data_download.create_books_table manual__2023-08-29T00:22:19.916454+00:00 [queued]>
[2023-08-29T00:22:21.648+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-29T00:22:21.665+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_books_table> on 2023-08-29 00:22:19.916454+00:00
[2023-08-29T00:22:21.672+0000] {standard_task_runner.py:57} INFO - Started process 142 to run task
[2023-08-29T00:22:21.679+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_data_download', 'create_books_table', 'manual__2023-08-29T00:22:19.916454+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/coin_data_dag.py', '--cfg-path', '/tmp/tmpthjagwft']
[2023-08-29T00:22:21.690+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask create_books_table
[2023-08-29T00:22:21.789+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_data_download.create_books_table manual__2023-08-29T00:22:19.916454+00:00 [running]> on host 6c9aee5df47e
[2023-08-29T00:22:21.916+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='crypto_data_download' AIRFLOW_CTX_TASK_ID='create_books_table' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:22:19.916454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T00:22:19.916454+00:00'
[2023-08-29T00:22:21.919+0000] {sql.py:274} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS books (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255),
        author VARCHAR(255)
    );
    
[2023-08-29T00:22:21.932+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-08-29T00:22:21.944+0000] {base.py:73} INFO - Using connection ID 'postgres_connection' for task execution.
[2023-08-29T00:22:21.946+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2023-08-29T00:22:21.959+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_data_download, task_id=create_books_table, execution_date=20230829T002219, start_date=20230829T002221, end_date=20230829T002221
[2023-08-29T00:22:21.974+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 97 for task create_books_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 142)
[2023-08-29T00:22:22.012+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T00:22:22.033+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
